# This is a basic workflow to help you get started with Actions

name: Jekyll Build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy to GitHub Pages
      uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

      
        
        
